In [1]:
import pandas as pd

df = pd.read_csv("orders.csv")

In [9]:
df.index

RangeIndex(start=0, stop=40, step=1)

In [17]:
df[["Country", "Product"]]

         Country                Product
0            USA                 Laptop
1         Canada             Headphones
2            UAE           Office Chair
3      Singapore              Desk Lamp
4         Mexico               Keyboard
5            UAE               Notebook
6             UK          Standing Desk
7    South Korea                Monitor
8          Italy                    Pen
9          Japan                  Mouse
10        France                 Webcam
11         India           File Cabinet
12     Australia                Stapler
13         Spain              USB Drive
14         China              Bookshelf
15         Egypt          Printer Paper
16        Poland         Wireless Mouse
17           USA         Desk Organizer
18         Japan             Calculator
19  Saudi Arabia             Whiteboard
20        Canada           Highlighters
21        Brazil      Bluetooth Speaker
22       Germany           Office Plant
23      Pakistan           Sticky Notes
24        Sweden           Tablet Stand
25        France         Paper Shredder
26     Argentina         Desk Chair Mat
27        Russia           Binder Clips
28   South Korea      Wireless Keyboard
29         Italy          Desk Calendar
30       Morocco                USB Hub
31       Germany       Document Scanner
32      Colombia  Desk Drawer Organizer
33           USA            Index Cards
34         Japan          Monitor Stand
35            UK     Desk Lamp with USB
36      Portugal       Wireless Earbuds
37          Iran               Desk Pad
38   South Korea            Power Strip
39       Ukraine             Desk Clock

In [29]:
df.iloc[0]["Product"]

'Laptop'

In [30]:
df.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

In [40]:
df[(df["Category"] == "Electronics") & (df["Country"] == "USA")] # This is a filter
# In my data frame, I want to look at all the values that match the given category

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA

In [39]:
df[(df["Category"] == "Electronics") | (df["Country"] == "USA")] # This is a filter
# In my data frame, I want to look at all the values that match the given category

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea